### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by Fuchsritter** [tipichris/bbcwx#22]
Hello,

I am using Linux Mint Cinnamon 64 bit 17.3.

I use the desklet on two computers. I use yahoo as data source. I can't change the language of the desklet. Some time ago I got German on one computer. But I failed to get German language at the second computer.

How can I change the language?

Best regards
Andreas

**Comment by tipichris** [comment]
The desklet should use the preferred language configured for your desktop, as long as it supports it (and it does support German). Check your desktop configuration. If you have only specific regional variations included in your language list (eg de_CH) and no generic (de) it may fail. If that is what is happening it is possibly a bug that needs looking at, but I assumed that everyone would configure a generic fallback in their list of preferred languages.

**Comment by Fuchsritter** [comment]
Thanks for your fast answer.

Mint was installed in German. Through the menu the languages are set to German UTF8

Locale on console shows:

LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=

/etc/default/locale

LANG=de_DE.UTF-8
LANGUAGE=de_DE:de
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_MONETARY=de_DE.UTF-8
LC_PAPER=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8

**Comment by Fuchsritter** [comment]
Hello,

I don't know why. The new desktop environments are difficult, so much config files and places.

I copied the /.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/ directory to the second computer.

I delete the desklet from desktop, deleted /.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/ and installed it again through the menu. And now it works. During installation something is made with languages.

So direct copy is not possible.

Thanks a lot for help.

**Comment by tipichris** [comment]
That's correct. This is a feature of the whole desklet framework, not just the Weather Desklet. On installation the .po files distributed with the desklet are compiled and the resulting .mo files are installed into ~/.share/locale
