### ISSUE TITLE
openweather :  error 401

### ISSUE THREAD

**Issue by sacrileger** [tipichris/bbcwx#25]
docs for openweather not accurate.  i didnt go to all links but this didnt work for me:
http://openweathermap.org/login (page not found)

openweather doesnt work as outlined in docs.
i.e. berlin [2950159] err: 401

[ http://openweathermap.org/city/2950159 ]

using coords [ 51.51,-0.13 ] doesnt work either

**Comment by muzena** [comment]
Neither Yahoo weather work.
Same error: error 401

**Comment by Alx31** [comment]
yup same here, error 401; no matter wich provider; using mint17./cinnamon 2.8.8.

is there a way to get a useful log?

**Comment by tipichris** [comment]
Openweather now require an API key. The bundled help file now reflects this and the link to the API registration page has been updated.

**Comment by Alx31** [comment]
thanks
