### ISSUE TITLE
Min and Max temperature no longer displayed

### ISSUE THREAD

**Issue by ThosV** [tipichris/bbcwx#30]
For some reason, my weather desklet no long displays the forcasted min and max temperatures. I haven't made any changes to it's configuration file or anything like that. 

I'm using the BBC weather service. 

Here are the relevant parts from the .config:
```

    "display__forecast__maximum_temperature": {
        "type": "checkbox",
        "default": true,
        "description": "Forecast maximum",
        "tooltip": "Check to display the forecast maximum temperature",
        "value": true
    },
    "display__forecast__minimum_temperature": {
        "type": "checkbox",
        "default": true,
        "description": "Forecast minimum",
        "tooltip": "Check to display the forecast minimum temperature",
        "value": true
    },
```

**Comment by tipichris** [comment]
Well that's annoying :( 

The [feed that the desklet uses](http://open.live.bbc.co.uk/weather/feeds/en/2634725/3dayforecast.rss) is returning 'null' for min and max. The BBC website currently points to a [different feed address](https://weather-broker-cdn.api.bbci.co.uk/en/forecast/rss/3day/2634725) which is returning max and min, but unfortunately some of the weather description strings have changed ('shower' has become 'showers' for example). 

To make things worse, the new [feed address for current observations](https://weather-broker-cdn.api.bbci.co.uk/en/observation/rss/2634725) has lots of other things missing. This may have to do with the BBC deciding it will no longer use the Met Office for its weather. I suspect they are in transition at the moment.

I'm going to keep an eye on this for a while and see how it settles down before pushing out an update.

Interestingly, the new service appears to include an undocumented JSON API which may prove handy. But with weather given as a code and no obvious list of what those codes mean it could take a while to figure out.

**Comment by thosvarley** [comment]
Is there a simple way I can point the desklet at the new feed? It's unfortunate that it's missing information, but I'd rather have min/max and loose wind direction for instance.

**Comment by tipichris** [comment]
Look at the branch bbc-changes in this repository. The only file you should need to replace is desklet.js. https://github.com/tipichris/bbcwx/tree/bbc-changes

**Comment by tipichris** [comment]
Changes to address this issue have now been made in the main linuxmint/cinnamon-spices-desklets
 repository
