### ISSUE TITLE
bbc weather working ...

### ISSUE THREAD

**Issue by quickgreyfox** [tipichris/bbcwx#32]
bbc weather data is displayed again with a lack of some items like pressure, wind and the current

 status. Thanks for your meticulous work!

**Comment by a114m** [comment]
BBC source is not working with me right now.

Still thanks for your time and effort.

**Comment by tipichris** [comment]
The BBC have changed their data endpoint. Changes addressing this issue have been made in the main linuxmint/cinnamon-spices-desklets repository. Please make sure that you are running the latest version.

Unfortunately, the BBC's new endpoints are not providing data for a number of current observations for many locations. This is outside the desklet's control, and probably relates to the BBC shifting weather data supplier from the Met Office to MeteoGroup
